export const GET_SPACE_PHOTOS_REQUEST =
    "SPACE_PHOTOS::GET_SPACE_PHOTOS_REQUEST";
export const GET_SPACE_PHOTOS_SUCCESS =
    "SPACE_PHOTOS::GET_SPACE_PHOTOS_SUCCESS";
export const GET_SPACE_PHOTOS_FAILURE =
    "SPACE_PHOTOS::GET_SPACE_PHOTOS_FAILURE";
export const GET_SPACE_PHOTOS_FULFILL =
    "SPACE_PHOTOS::GET_SPACE_PHOTOS_FULFILL";
